
name: 'dbt_reconciliation'
version: '1.0.0'

profile: 'dbt_reconciliation'

vars:
  reconciliation_tolerance: 0.01


model-paths: ["models"]
test-paths: ["tests"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
